include("consts.jl");
include("error_ms.jl");
include("aux_data_format.jl")
include("build_aux_file_path.jl");
include("read_aux_data.jl");
include("validate_aux_file.jl");
include("validate_aux_data.jl");
include("getters.jl");
include("setters.jl");
include("save_aux_data.jl");
include("create_aux_file.jl");
